language: ruby
rvm:
 - 2.7.1

install:
    - bundle install
    - nvm install node
    - node -v
    - npm i -g yarn
    - yarn install

before_install:
    gem install bundler
    
script:
    - bundle exec rails webpacker:compile RAILS_ENV=test
    - bundle exec rails db:create RAILS_ENV=test
    - bundle exec rails db:migrate RAILS_ENV=test
    - bundle exec rspec

services: 
    - postgresql