 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/phones", type: :request do
  let(:person) { FactoryBot.create(:person) }
  # Phone. As you add validations to Phone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      phone_number: "000000000",
      person_id: person.id,
    }
  }

  let(:invalid_attributes) {
    {
      phone_number: nil,
      person_id: nil,
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      skip("Now nested under people#show")
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      phone = Phone.create! valid_attributes
      get person_phone_url(person, phone)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_person_phone_url(person)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      phone = Phone.create! valid_attributes
      get edit_person_phone_url(person, phone)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Phone" do
        expect {
          post person_phones_url(person), params: { phone: valid_attributes }
        }.to change(Phone, :count).by(1)
      end

      it "redirects to the created phone" do
        post person_phones_url(person), params: { phone: valid_attributes }
        expect(response).to redirect_to(person_url(person))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Phone" do
        expect {
          post person_phones_url(person), params: { phone: invalid_attributes }
        }.to change(Phone, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post person_phones_url(person), params: { phone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          phone_number: "111222333",
        }
      }

      it "updates the requested phone" do
        phone = Phone.create! valid_attributes
        patch person_phone_url(person, phone), params: { phone: new_attributes }
        phone.reload
        expect(phone.phone_number).to eq("111222333")
      end

      it "redirects to the phone" do
        phone = Phone.create! valid_attributes
        patch person_phone_url(person, phone), params: { phone: new_attributes }
        phone.reload
        expect(response).to redirect_to(person_url(person))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        phone = Phone.create! valid_attributes
        patch person_phone_url(person, phone), params: { phone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested phone" do
      phone = Phone.create! valid_attributes
      expect {
        delete person_phone_url(person, phone)
      }.to change(Phone, :count).by(-1)
    end

    it "redirects to the phones list" do
      phone = Phone.create! valid_attributes
      delete person_phone_url(person, phone)
      expect(response).to redirect_to(person_url(person))
    end
  end
end
